playlist/urls.py
from django.urls import path
from . import views

app_name="playlist"
urlpatterns=[
    path("",views.index,name="index"),
    path("add",views.add,name="add"),
    #path("download",views.download,name="download")
    #path("Prog",views.Prog)
    #adding path to download function in views callable by playlist:download, with filename argument
    path("download/<str:filename>",views.download,name="download")
    
]

users/urls.py
from django.urls import path

from . import views

app_name="users"

urlpatterns=[
    path("", views.index,name="index"),
    path("login",views.login_view,name="login"),
    path("logout",views.logout_view,name="logout"),
    path("register",views.register_request,name="register")
]

webBack/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('hello/', include("hello.urls")),
    path('playlist/', include("playlist.urls")),
    path('users/', include("users.urls"))
]

playlist/models.py
from django.db import models

# Create your models here.
#one model for each of the tables
class Use(models.Model):
    username=models.CharField(max_length=60)
    password=models.CharField(max_length=60)



#model to save the playlist name, uri, and playlist logo
class Playlist(models.Model):
    id=models.AutoField(primary_key=True)
    playName=models.CharField(max_length=120)
    playUri=models.CharField(max_length=240)
    use=models.CharField(max_length=60,default='anon')
    #logo is prob just a link 
    #add logo here

    def __str__(self):
        return f"ID is {self.id} Name is {self.playName}, link is {self.playUri}, username is {self.use}"

playlist/views.py
from django.shortcuts import render,redirect
from django import forms
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from django.http import HttpResponse
import os
import shutil
from django.conf import settings
from .models import Use,Playlist
from django.core import serializers

#playlistname=["default"]
#username=[""]

class newPlaylistForm(forms.Form):
    playlist=forms.CharField(label="Playlist Link", widget=forms.TextInput(attrs={'class':'new__input','placeholder': 'Playlist Link'}))
    
    #label="Playlist Link",
    #label="PlaylistNameENG",
    #remove from here
    #name=forms.CharField(label="Your Name")
    #clientID=forms.CharField(label="Client ID")
    #clientSecret=forms.CharField(label="Client Secret")
    #to here
    playlistENG=forms.CharField(label="Playlist Name", widget=forms.TextInput(attrs={'class':'new__input','placeholder': 'Playlist Name'}))

# Create your views here.
def index(request):
    if "playlistname" not in request.session:
        request.session["playlistname"]=["default"]
    #remove from here
   # if "username" not in request.session:
   #     request.session["username"]=[""]
   # if "clientID" not in request.session:
   #     request.session["clientID"]=[""]
   # if "clientSecret" not in request.session:
   #     request.session["clientSecret"]=[""]
    #to here
    if "playlistENG" not in request.session:
        request.session["playlistENG"]=[""]
    
    last_ten = Playlist.objects.all().order_by('-id')[:10]
    return render(request,"playlist/index.html",{
        "playlistname":request.session["playlistname"],
        "playlistENG":request.session["playlistENG"],
        "playlistListed":last_ten
    })

def add(request):
    if request.method=="POST":
        form=newPlaylistForm(request.POST)
        if form.is_valid():
            newPlaylist=form.cleaned_data["playlist"]
            temp=newPlaylist
            #parse the url here for the uri. then set newPlaylist to that string
            if "playlist" in newPlaylist:
                newPlaylist=newPlaylist.split("playlist/",1)[1]
                newPlaylist=newPlaylist.split("?",1)[0]
            #if "album" in newPlaylist:
                #newPlaylist=newPlaylist.split("album/",1)[1]
                #newPlaylist=newPlaylist.split("?",1)[0]
            request.session["playlistname"]=[newPlaylist]


            #remove from here
          #  newname=form.cleaned_data["name"]
          #  request.session["username"]=[newname]
          #  newCID=form.cleaned_data["clientID"]
          #  request.session["clientID"]=[newCID]
          #  newCS=form.cleaned_data["clientSecret"]
          #  request.session["clientSecret"]=[newCS]
            #to here

            playENG=form.cleaned_data["playlistENG"]
            request.session["playlistENG"]=[playENG]

            #username=1245041861
            #clientID=98bef7ae82bb43c3aed3a6090278b930
            #clientsecret=7fe0a4d0d57c41878f9e119c902a7072
            
            #print(f"webBack/playlist/spotifytomp32/spotify_to_mp3.py {newCID} {newCS} {newname} {newPlaylist}")


            #call with hard coded ClientID ClientSecret and Username
            #os.system(f"python C:/Users/sherg/OneDrive/Documents/TestProject/webBack/playlist/spotifytomp32/spotify_to_mp3.py {newCID} {newCS} {newname} {newPlaylist}")
            os.system(f"python C:/Users/sherg/OneDrive/Documents/TestProject/webBack/playlist/spotifytomp32/spotify_to_mp3.py 98bef7ae82bb43c3aed3a6090278b930 7fe0a4d0d57c41878f9e119c902a7072 1245041861 {newPlaylist}")
            
            #make this work with other playlistENG names DONE
            shutil.make_archive('playlist/zipPlaylist','zip', f'C:/Users/sherg/OneDrive/Documents/TestProject/webBack/{playENG}')



            ###insert or add to existing python script, to grab the playlist picture.
            ###insert database add here, insert into playlist model, the playlist name and the playlist link
            playlistData=Playlist()
            playlistData.playName=playENG
            playlistData.playUri=temp
            if request.user.is_authenticated:
                playlistData.use=request.user.username
            playlistData.save()

            #Clean up txt file and the folder after. os.remove for txt file and os.rmdir for folder
            shutil.rmtree(f'{playENG}', ignore_errors=True)

            #print("COMPLETED ALL OPERATIONS!",request.session["playlistname"],request.session["username"],request.session["clientID"],request.session["clientSecret"])
            
            last_ten = Playlist.objects.all().order_by('-id')[:10]
            #last_ten_in_ascending_order = reversed(last_ten)
            last_ten_in_ascending_order=last_ten
            #return HttpResponseRedirect(reverse("playlist:index"))
            #request.session['recent']=serializers.serialize("xml",last_ten)
            #request.session['recent']=last_ten.values_list('id')
            #x=last_ten
            return redirect('playlist:index')

          #  return render(request,"playlist/index.html",{
           #     #"playlistsListed":Playlist.objects.all()
           #     #"playlistsListed":Playlist.objects.filter(id_gte=(i-10))
           #     "playlistsListed":last_ten_in_ascending_order
           # })
            
        else:
            return render(request, "playlist/add.html",{
                "form":form
            })
    return render(request, "playlist/add.html",{
        "form": newPlaylistForm()
    })



def download(request,filename):
    file_path=os.path.join(settings.MEDIA_ROOT,f"playlist/{filename}")
    print(file_path)
    if os.path.exists(file_path):
        with open(file_path,'rb') as fh:
            response=HttpResponse(fh.read(),content_type="application/zip")
            response['Content-Disposition']='inline; filename='+os.path.basename(file_path)
            return response
    raise Http404

playlist/templates/playlist/add.html
{% extends "playlist/layout.html" %}

{% block body %}
    <h3>Add Playlist</h3>
    <form action="{% url 'playlist:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input class="main__btn" type="submit">
    </form>
    <a class="navbar___item" href="{% url 'playlist:index' %}">View playlist</a>
{% endblock %}

playlist/templates/playlist/download.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Download</title>
</head>
<body>
    <h1>Download your playlist folder!</h1>
    {% for play in playlistENG %}
    <a href="{% url 'playlist:download' filename='zipPlaylist.zip' %}">Download!</a>
    {% endfor %}
</body>
</html>

playlist/templates/playlist/index.html
{% extends "playlist/layout.html" %}

    
{% block body %}
    <h3>PLAYLIST:</h3>
    {% for playlist in playlistENG %}
        <h3>{{playlist}}</h3>
    {% endfor %}
    {% if playlistENG.0 != "" %}
    <!---
    <a class="navbar___item" href="{% url 'playlist:download' filename='zipPlaylist.zip' %}">Download!</a>-->
    <form action="{% url 'playlist:download' filename='zipPlaylist.zip' %}">
        <button class=main__btn type="submit">Download!</button>
    </form>
    {% endif %}



    <a class="navbar___item" href="{% url 'playlist:add' %}">Add a new playlist</a>
    <!--
    {% for item in playlistListed %}
    <ul>
        <li>{{item}}</li>
    </ul>
    {% endfor %}
-->
    <script>
        function copyLink(){
            var copyText=document.getElementById("Recent_Playlists");
            var para=document.getElementById("Link_Para");
            //var link=document.getElementById("link_button");
            //link.value="Get Link to "+copyText.
            para.innerHTML=copyText.value;

            //alert("Here is the link: "+copyText.value);
        }
    </script>
    <form id="frm1">
        <label for="Recent_Playlists">Recently Downloaded Playlists</label>
        <select name="Recent_Playlists" id="Recent_Playlists">
            {% for item in playlistListed %}
                <option value="{{item.playUri}}">{{item.playName}}</option>
            {% endfor %}
        </select>
        <br><br>
        <input id="link_button" type="button" value="Get Link!" onclick="copyLink()">
    </form>
    <div id="Link_Para"></div>
{% endblock %}

playlist/templates/playlist/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spotify2mp3</title>
    
    <link rel="stylesheet" href="styles.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@400;700&display=swap" rel="stylesheet">
    <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.4.min.js"></script> 
</head>
<body>
    <!-- Navbar Section -->
    <nav class="navbar">
        <div class="navbar__container">
            <a href="{% url 'playlist:index' %}" id="navbar__logo"><i class="fas fa-gem"></i>Spotify2mp3 </a>
            <div class="navbar__toggle" id="mobile-menu">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </div>
            <ul class="navbar__menu">
                <!--
                <li class="navbar__item">
                    <a href="/" class="navbar__links">
                        Home
                    </a>
                </li>
                <li class="navbar__item">
                    <a href="/tech.html" class="navbar__links">
                        Tech
                    </a>
                </li>
            -->
            {% if not user.is_authenticated %}
                <li class="navbar__item">
                    <a href="{% url 'users:login' %}" class="navbar__links">
                        Login
                    </a>
                </li>
                <li class="navbar__btn">
                    <a href="{% url 'users:register' %}" class="button">
                        Sign Up
                    </a>
                </li>
            {% else %}
                <li class="navbar__btn">
                    <a href="{% url 'users:index' %}" class="button">
                        My Account
                    </a>
                </li>

            {% endif %}
            </ul>
        </div>
    </nav>
    
    <!-- Hero Section -->
    <div class="main">
        <div class="main__container">
            <div class="main__content">
                <h1>Spotify to .mp3</h1>
                <!--
                <h2>Youtube</h2>-->
                <p>Download Entire Spotify Playlists.</p>
                <!--
                <button class="main__btn"><a href="/">Get Started</a></button>
                -->
                {% block body %}
                {% endblock %}
                <!--
                <form>
                    <input class="new__input" autocomplete="off" autofocus id="name" placeholder="Playlist" type="text">
                    <button class="main__btn" type="submit"><a href="/">DOWNLOAD</a></button>
                </form>
                -->
            </div>
            <div class="main__img--container">
                <img src="{% static 'images/pic5.png' %}" alt="pic" id="main__img">
            </div>
        </div>
    </div>

    <!-- Services Section -->
    <!--
    <div class="services">
        <h1>See what the hype is about</h1>
        <div class="services__container">
            <div class="services__card">
                <h2>Experience Bliss</h2>
                <p>AI Powered Technology</p>
                <button>Get Started</button>
            </div>
            <div class="services__card">
                <h2>Are you Ready?</h2>
                <p>Take the Leap</p>
                <button>Get Started</button>
            </div>
        </div>
    </div>-->

    <!-- Footer Section -->
    <div class="footer__container">
        <div class="footer__links">
            <div class="footer__link--wrapper">
                <div class="footer__link--items">
                    <h2>About Us</h2>
                    <a href="/">How it works</a>
                    <a href="/">Testimonials</a>
                    <a href="/">Careers</a>
                    <a href="/">Investments</a>
                    <a href="/">Terms of Service</a>
                </div>
                <div class="footer__link--items">
                    <h2>Contact Us</h2>
                    <a href="/">Contact</a>
                    <a href="/">Support</a>
                    <a href="/">Destinations</a>
                    <a href="/">Sponsorsihps</a>
                </div>
            </div>
            <div class="footer__link--wrapper">
                <div class="footer__link--items">
                    <h2>Videos</h2>
                    <a href="/">Submit</a>
                    <a href="/">Video</a>
                    <a href="/">Ambassadors</a>
                    <a href="/">Agency</a>
                    <a href="/">Influencer</a>
                </div>
                <div class="footer__link--items">
                    <h2>Social Media</h2>
                    <a href="/">Twitter</a>
                    <a href="/">Youtube</a>
                    <a href="/">Instagram</a>
                    <a href="/">LinkedIn</a>
                    <a href="/">Facebook</a>
                </div>
            </div>
        </div>
        <section class="social__media">
            <div class="social__media--wrap">
                <div class="footer__logo">
                    <a href="/" id="footer__logo"><i class="fas fa-gem"></i>Spotify2mp3</a>
                </div>
                <p class="website__right">Spotify2mp3 2020. All rights reserved</p>
                <div class="social__icons">
                    <a href="/" class="social__icon--link" target="_blank">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a href="/" class="social__icon--link" target="_blank">
                        <i class="fab fa-youtube"></i>
                    </a>
                    <a href="/" class="social__icon--link" target="_blank">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a href="/" class="social__icon--link" target="_blank">
                        <i class="fab fa-linkedin"></i>
                    </a>
                    <a href="/" class="social__icon--link" target="_blank">
                        <i class="fab fa-facebook"></i>
                    </a>
                </div>
            </div>
        </section>
    </div>
    
    <script src="{% static 'appl.js' %}"></script>
    <script src="appl.js"></script>
</body>
</html>