playlist/urls.py
from django.urls import path
from . import views

app_name="playlist"
urlpatterns=[
    path("",views.index,name="index"),
    path("add",views.add,name="add"),
    #path("download",views.download,name="download")
    #path("Prog",views.Prog)
    #adding path to download function in views callable by playlist:download, with filename argument
    path("download/<str:filename>",views.download,name="download")
    
]

users/urls.py
from django.urls import path

from . import views

app_name="users"

urlpatterns=[
    path("", views.index,name="index"),
    path("login",views.login_view,name="login"),
    path("logout",views.logout_view,name="logout"),
    path("register",views.register_request,name="register")
]

webBack/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('hello/', include("hello.urls")),
    path('playlist/', include("playlist.urls")),
    path('users/', include("users.urls"))
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
    email=forms.EmailField(required=True)

    class Meta:
        model=User
        fields=("username","email","password1","password2")
    def save(self,commit=True):
        user=super(NewUserForm,self).save(commit=False)
        user.email=self.cleaned_data['email']
        if commit:
            user.save()
        return user
    

users/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from .forms import NewUserForm
from django.contrib import messages
from django.apps import apps
# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return redirect("users:login")
        #return HttpResponseRedirect(reverse("login"))
    Playlist=apps.get_model('playlist','Playlist')
    last_ten = Playlist.objects.filter(use=request.user.username).order_by('-id')[:10]
    return render(request, "users/user.html",{
        "playlistListed":last_ten
    })
    
def login_view(request):
    if request.method=="POST":
        username=request.POST["username"]
        password=request.POST["password"]
        #print(username,password)
        user = authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect("users:index")
        else:
            return render(request,"users/login.html",{
                "message":"Invalid credentials."
            })
    
    return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    return render(request,"users/login.html",{
        "message":"Logged Out."
    })
    

def register_request(request):
    if request.method=="POST":
        form=NewUserForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            messages.success(request,"Registration successful.")
            return redirect("users:index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form= NewUserForm()
    return render(request=request,template_name="users/register.html",context={"register_form":form})

users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spotify2mp3</title>
    
    <link rel="stylesheet" href="styles.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> 
    <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
</head>
<body>
    <!-- Navbar Section -->
    <nav class="navbar">
        <div class="navbar__container">
            <a href="{% url 'playlist:index' %}" id="navbar__logo"><i class="fas fa-gem"></i>Spotify2mp3 </a>
            <div class="navbar__toggle" id="mobile-menu">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </div>
            <ul class="navbar__menu">
                <!--
                <li class="navbar__item">
                    <a href="/" class="navbar__links">
                        Home
                    </a>
                </li>
                <li class="navbar__item">
                    <a href="/tech.html" class="navbar__links">
                        Tech
                    </a>
                </li>
            -->
            {% if not user.is_authenticated %}
                <li class="navbar__item">
                    <a href="{% url 'users:login' %}" class="navbar__links">
                        Login
                    </a>
                </li>
                <li class="navbar__btn">
                    <a href="{% url 'users:register' %}" class="button">
                        Sign Up
                    </a>
                </li>
            {% else %}
                <li class="navbar__btn">
                    <a href="{% url 'users:index' %}" class="button">
                        My Account
                    </a>
                </li>

            {% endif %}

            </ul>
        </div>
    </nav>
    
    <!-- Hero Section -->
    <div class="main">
        <div class="main__container">
            <div class="main__content">
                <h1>Spotify to .mp3</h1>
                <!--
                <h2>Youtube</h2>-->
                <p>Download Entire Spotify Playlists.</p>
                <!--
                <button class="main__btn"><a href="/">Get Started</a></button>
                -->
                {% block body %}
                {% endblock %}
                <!--
                <form>
                    <input class="new__input" autocomplete="off" autofocus id="name" placeholder="Playlist" type="text">
                    <button class="main__btn" type="submit"><a href="/">DOWNLOAD</a></button>
                </form>
                -->
            </div>
            <div class="main__img--container">
                <img src="{% static 'images/pic5.png' %}" alt="pic" id="main__img">
            </div>
        </div>
    </div>

    <!-- Services Section -->
    <!--
    <div class="services">
        <h1>See what the hype is about</h1>
        <div class="services__container">
            <div class="services__card">
                <h2>Experience Bliss</h2>
                <p>AI Powered Technology</p>
                <button>Get Started</button>
            </div>
            <div class="services__card">
                <h2>Are you Ready?</h2>
                <p>Take the Leap</p>
                <button>Get Started</button>
            </div>
        </div>
    </div>-->

    <!-- Footer Section -->
    <div class="footer__container">
        <div class="footer__links">
            <div class="footer__link--wrapper">
                <div class="footer__link--items">
                    <h2>About Us</h2>
                    <a href="/">How it works</a>
                    <a href="/">Testimonials</a>
                    <a href="/">Careers</a>
                    <a href="/">Investments</a>
                    <a href="/">Terms of Service</a>
                </div>
                <div class="footer__link--items">
                    <h2>Contact Us</h2>
                    <a href="/">Contact</a>
                    <a href="/">Support</a>
                    <a href="/">Destinations</a>
                    <a href="/">Sponsorsihps</a>
                </div>
            </div>
            <div class="footer__link--wrapper">
                <div class="footer__link--items">
                    <h2>Videos</h2>
                    <a href="/">Submit</a>
                    <a href="/">Video</a>
                    <a href="/">Ambassadors</a>
                    <a href="/">Agency</a>
                    <a href="/">Influencer</a>
                </div>
                <div class="footer__link--items">
                    <h2>Social Media</h2>
                    <a href="/">Twitter</a>
                    <a href="/">Youtube</a>
                    <a href="/">Instagram</a>
                    <a href="/">LinkedIn</a>
                    <a href="/">Facebook</a>
                </div>
            </div>
        </div>
        <section class="social__media">
            <div class="social__media--wrap">
                <div class="footer__logo">
                    <a href="/" id="footer__logo"><i class="fas fa-gem"></i>Spotify2mp3</a>
                </div>
                <p class="website__right">Spotify2mp3 2020. All rights reserved</p>
                <div class="social__icons">
                    <a href="/" class="social__icon--link" target="_blank">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a href="/" class="social__icon--link" target="_blank">
                        <i class="fab fa-youtube"></i>
                    </a>
                    <a href="/" class="social__icon--link" target="_blank">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a href="/" class="social__icon--link" target="_blank">
                        <i class="fab fa-linkedin"></i>
                    </a>
                    <a href="/" class="social__icon--link" target="_blank">
                        <i class="fab fa-facebook"></i>
                    </a>
                </div>
            </div>
        </section>
    </div>
    
    <script src="{% static 'appl.js' %}"></script>
    <script src="appl.js"></script>
</body>
</html>

users/templates/users/login.html
{% extends "users/layout.html" %}

{% block body %}

    {% if message %}
        <div>{{message}}</div>
    {% endif %}
    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" value="Login">
    </form>

    <a class="navbar___item" href="{% url 'playlist:index' %}">Back to Playlists</a>

{% endblock %}

users/templates/users/register.html
{% extends "users/layout.html" %}

{% block body %}

    <div class="container py-5">
        <h1>Register</h1>
        <form method="POST">
            {% csrf_token %}
            {{register_form}}
            <button class="btn btn-primary" type="submit">Register</button>
        </form>
        <p class="text-center">If you already have an account, <a href="{% url 'users:login' %}">login</a>instead.</p>
    </div>

{% endblock %}

users/templates/users/user.html
{% extends "users/layout.html" %}

{% block body %}

    <p>Welcome, {{ request.user.username }}</p>

    <a class="navbar___item" href="{% url 'users:logout' %}">Log Out</a>

    <a class="navbar___item" href="{% url 'playlist:index' %}">Back to Playlists</a>

<!--
    {% for item in playlistListed %}
    <ul>
        <li>{{item}}</li>
    </ul>
    {% endfor %}
-->
    <script>
        function copyLink(){
            var copyText=document.getElementById("Recent_Playlists");
            var para=document.getElementById("Link_Para");
            //var link=document.getElementById("link_button");
            //link.value="Get Link to "+copyText.
            para.innerHTML=copyText.value;

            //alert("Here is the link: "+copyText.value);
        }
    </script>
    <form id="frm1">
        <label for="Recent_Playlists">My Recently Downloaded Playlists</label>
        <select name="Recent_Playlists" id="Recent_Playlists">
            {% for item in playlistListed %}
                <option value="{{item.playUri}}">{{item.playName}}</option>
            {% endfor %}
        </select>
        <br><br>
        <input id="link_button" type="button" value="Get Link!" onclick="copyLink()">
    </form>
    <div id="Link_Para"></div>
{% endblock %}